# Generated by Django 3.2.18 on 2023-03-05 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ps_stripe', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='сlient',
            new_name='client',
        ),
    ]
