# Generated by Django 3.2.18 on 2023-03-05 15:27

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import subscriptions.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly')], default='month', max_length=5)),
                ('role_name', models.CharField(help_text='A role name from Auth Service', max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('int_price', models.IntegerField(help_text='Storing in cents')),
                ('currency', subscriptions.fields.CurrencyField(choices=[('rub', 'Rub')], default='rub', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_name', models.CharField(max_length=255)),
                ('int_payment_amount', models.IntegerField(help_text='Storing in cents')),
                ('currency', subscriptions.fields.CurrencyField(choices=[('rub', 'Rub')], default='rub', max_length=3)),
                ('payment_dt', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
            ],
            options={
                'verbose_name_plural': 'Payments history',
            },
        ),
        migrations.CreateModel(
            name='ClientSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('auto_renewal', models.BooleanField(default=True)),
                ('payment_system_subscription_id', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscription')),
            ],
        ),
        migrations.AddConstraint(
            model_name='clientsubscription',
            constraint=models.UniqueConstraint(fields=('client', 'subscription'), name='client_subscription_client_subscription_unique'),
        ),
        migrations.AddConstraint(
            model_name='clientsubscription',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lte', django.db.models.expressions.F('end_date'))), name='client_subscription_start_date_le_end_date'),
        ),
    ]
