# Generated by Django 4.1.7 on 2023-02-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_create_model_subscription_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.IntegerField(default=0, help_text='Stores cents'),
            preserve_default=False,
        ),
    ]
