# Generated by Django 3.2.18 on 2023-03-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_table_client_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsubscription',
            name='payment_system_subscription_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_dt',
            field=models.DateTimeField(),
        ),
    ]
