# Generated by Django 3.2.18 on 2023-02-27 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_create_model_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionhistory',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='subscriptions.user'),
            preserve_default=False,
        ),
    ]
