# Generated by Django 3.2.18 on 2023-03-14 08:09

from django.db import migrations, models
import subscriptions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_clientsubscription_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='currency',
            field=subscriptions.fields.CurrencyField(choices=[('rub', 'руб.')], default='rub', max_length=3),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='currency',
            field=subscriptions.fields.CurrencyField(choices=[('rub', 'руб.')], default='rub', max_length=3),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='duration',
            field=models.CharField(choices=[('month', 'месяц'), ('year', 'год')], default='month', max_length=5),
        ),
    ]
