# Generated by Django 3.2.18 on 2023-03-19 10:04

import django.db.models.deletion
from django.db import migrations, models

import subscriptions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_translation'),
        ('subscriptions', '0006_models_choices_translation_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientsubscription',
            options={'verbose_name': 'Подписка клиента', 'verbose_name_plural': 'Подписки клиентов'},
        ),
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'verbose_name': 'История подписки', 'verbose_name_plural': 'История подписок'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterField(
            model_name='clientsubscription',
            name='auto_renewal',
            field=models.BooleanField(default=True, verbose_name='Автопродление'),
        ),
        migrations.AlterField(
            model_name='clientsubscription',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='clientsubscription',
            name='end_date',
            field=models.DateField(verbose_name='Окончание действия'),
        ),
        migrations.AlterField(
            model_name='clientsubscription',
            name='payment_system_subscription_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='ID из платежного сервиса'),
        ),
        migrations.AlterField(
            model_name='clientsubscription',
            name='start_date',
            field=models.DateField(verbose_name='Начало действия'),
        ),
        migrations.AlterField(
            model_name='clientsubscription',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientsubscription', to='subscriptions.subscription', verbose_name='Подписка'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='currency',
            field=subscriptions.fields.CurrencyField(choices=[('rub', 'руб.')], default='rub', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='int_payment_amount',
            field=models.IntegerField(help_text='Хранится в копейках', verbose_name='Сумма платежа'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_dt',
            field=models.DateTimeField(verbose_name='Дата и время платежа'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='subscription_name',
            field=models.CharField(max_length=255, verbose_name='Название подписки'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='currency',
            field=subscriptions.fields.CurrencyField(choices=[('rub', 'руб.')], default='rub', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='duration',
            field=models.CharField(choices=[('month', 'месяц'), ('year', 'год')], default='month', max_length=5, verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='int_price',
            field=models.IntegerField(help_text='Хранится в копейках', verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='role_name',
            field=models.CharField(help_text='Название роли из сервиса авторизации', max_length=255, verbose_name='Название роли'),
        ),
    ]
