# Generated by Django 3.2.18 on 2023-02-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_models_refactoring'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'verbose_name_plural': 'Payments history'},
        ),
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='payment_amount',
            new_name='int_payment_amount',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='price',
            new_name='int_price',
        ),
    ]
