# Generated by Django 3.2.18 on 2023-03-02 14:06

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_alter_user_subscription'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usersubscription',
            name='user_subscription_unique',
        ),
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.UniqueConstraint(fields=('user', 'subscription'), name='user_subscription_user_subscription_unique'),
        ),
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lte', django.db.models.expressions.F('end_date'))), name='user_subscription_start_date_le_end_date'),
        ),
    ]
