# Generated by Django 3.2.18 on 2023-03-04 18:03

from django.db import migrations
import subscriptions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_add_constraints_to_user_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='token',
            new_name='payment_system_subscription_id',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='currency',
            field=subscriptions.fields.CurrencyField(choices=[('643', 'Rub')], default='643', max_length=104),
        ),
        migrations.AddField(
            model_name='subscription',
            name='currency',
            field=subscriptions.fields.CurrencyField(choices=[('643', 'Rub')], default='643', max_length=104),
        ),
    ]
