# Generated by Django 3.2.18 on 2023-03-04 18:17

from django.db import migrations
import subscriptions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_field_currency_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='currency',
            field=subscriptions.fields.CurrencyField(choices=[('643', 'Rub')], default='643', max_length=3),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='currency',
            field=subscriptions.fields.CurrencyField(choices=[('643', 'Rub')], default='643', max_length=3),
        ),
    ]
