# Generated by Django 3.2.18 on 2023-03-05 09:07

from django.db import migrations, models
import subscriptions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_field_currency_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_system_customer_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='currency',
            field=subscriptions.fields.CurrencyField(choices=[('rub', 'Rub')], default='rub', max_length=3),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='currency',
            field=subscriptions.fields.CurrencyField(choices=[('rub', 'Rub')], default='rub', max_length=3),
        ),
    ]
