# Generated by Django 3.2.18 on 2023-03-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_alter_table_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='months_duration',
        ),
        migrations.AddField(
            model_name='subscription',
            name='duration',
            field=models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly')], default='month', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='payment_system_customer_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
