import os

BILLING_BASE_URL = os.environ.get('BILLING_BASE_URL')
BILLING_SUBSCRIPTIONS_ENDPOINT = os.environ.get('BILLING_SUBSCRIPTIONS_ENDPOINT')
BILLING_CLIENTS_ENDPOINT = os.environ.get('BILLING_CLIENTS_ENDPOINT')
BILLING_AUTH_TOKEN_COOKIE_NAME = os.environ.get('BILLING_AUTH_TOKEN_COOKIE_NAME', 'auth_token')
